;this file for FamiTone2 libary generated by nsf2data tool

	.export	_sfx_sounds
_sfx_sounds:
	.word @ntsc
	.word @pal
@ntsc:
	.word @sfx_ntsc_0
        .word @sfx_ntsc_1
@pal:
	.word @sfx_pal_0
        .word @sfx_pal_1

@sfx_ntsc_0:
	.byte $86,$81,$87,$6a,$88,$00,$01,$87,$70,$01,$87,$6a,$01,$87,$70,$01
	.byte $87,$6a,$01,$00
@sfx_pal_0:
	.byte $86,$81,$87,$62,$88,$00,$01,$87,$68,$01,$87,$62,$01,$87,$68,$01
	.byte $87,$62,$01,$00

@sfx_ntsc_1:
	.byte $89,$3f,$8a,$0b,$01,$89,$3a,$01,$89,$38,$01,$89,$36,$01,$89,$35
	.byte $8a,$0c,$01,$89,$34,$01,$89,$33,$02,$89,$32,$03,$89,$31,$04,$00

@sfx_pal_1:
	.byte $89,$3f,$8a,$0b,$01,$89,$3a,$01,$89,$38,$01,$89,$36,$01,$89,$35
	.byte $8a,$0c,$01,$89,$34,$01,$89,$33,$02,$89,$32,$03,$89,$31,$04,$00
