;this file for FamiTone2 libary generated by nsf2data tool

	.export	_sfx_sounds
_sfx_sounds:
	.word @ntsc
	.word @pal
@ntsc:
	.word @sfx_ntsc_0
@pal:
	.word @sfx_pal_0

@sfx_ntsc_0:
	.byte $86,$81,$87,$6a,$88,$00,$01,$87,$70,$01,$87,$6a,$01,$87,$70,$01
	.byte $87,$6a,$01,$00
@sfx_pal_0:
	.byte $86,$81,$87,$62,$88,$00,$01,$87,$68,$01,$87,$62,$01,$87,$68,$01
	.byte $87,$62,$01,$00
